<script setup lang="ts">
useSeoMeta({ title: 'NEO REDES', description: 'Conoce cómo NEO REDES gestiona la información facilitada a través de su sitio web y canales de contacto.' })
const updatedAt = '26 de agosto de 2026'
const sections = [
  { id: 'introduccion', title: 'Introducción', paragraphs: ['Esta política explica de forma general cómo NEO REDES gestiona la información que las personas facilitan voluntariamente al utilizar este sitio web o comunicarse por los canales habilitados.'] },
  { id: 'informacion-recopilada', title: 'Información que puede recopilarse', paragraphs: ['Podemos recibir datos de identificación y contacto, información sobre una empresa, marca o proyecto y cualquier contenido que la persona decida compartir al solicitar información o servicios.'], items: ['Nombre o identificación suministrada por la persona.', 'Correo electrónico o número de contacto.', 'Información necesaria para comprender una solicitud o proyecto.'] },
  { id: 'obtencion-informacion', title: 'Cómo se obtiene la información', paragraphs: ['La información se obtiene principalmente cuando una persona se comunica voluntariamente mediante WhatsApp, correo electrónico, redes sociales u otros canales que NEO REDES habilite y anuncie expresamente.'] },
  { id: 'finalidades', title: 'Finalidades del tratamiento', paragraphs: ['La información podrá utilizarse para responder consultas, preparar propuestas, mantener comunicaciones relacionadas con servicios solicitados, ejecutar acuerdos celebrados y atender obligaciones aplicables. No se utilizará para finalidades incompatibles sin informar o solicitar autorización cuando corresponda.'] },
  { id: 'uso-sitio-web', title: 'Uso del sitio web', paragraphs: ['El sitio presenta información institucional, servicios y medios de contacto. No se identificaron registros de usuarios, comercio electrónico ni áreas privadas dentro de la implementación actual.'] },
  { id: 'cookies', title: 'Cookies y tecnologías similares', paragraphs: ['En la revisión actual del proyecto no se encontraron herramientas propias de analítica, píxeles publicitarios ni mecanismos de seguimiento no esencial. Si esta situación cambia, la política deberá actualizarse y se implementarán los avisos o controles que correspondan.'] },
  { id: 'servicios-terceros', title: 'Servicios de terceros', paragraphs: ['El sitio puede incluir enlaces a servicios externos, como WhatsApp y redes sociales. Al acceder a ellos se aplican sus propias condiciones y políticas. NEO REDES no controla el tratamiento realizado directamente por esos terceros.'] },
  { id: 'conservacion', title: 'Conservación de información', paragraphs: ['La información se conservará únicamente durante el tiempo razonablemente necesario para atender la finalidad que motivó su recepción, cumplir acuerdos u obligaciones aplicables y gestionar solicitudes posteriores. Los plazos concretos dependerán de cada relación y del marco aplicable.'] },
  { id: 'seguridad', title: 'Seguridad de la información', paragraphs: ['NEO REDES procurará aplicar medidas razonables de carácter administrativo y técnico para reducir riesgos de pérdida, acceso no autorizado, alteración o divulgación. Ningún sistema puede garantizar seguridad absoluta.'] },
  { id: 'derechos', title: 'Derechos de los titulares', paragraphs: ['Las personas podrán solicitar información sobre sus datos, pedir su actualización o corrección y formular solicitudes relacionadas con su tratamiento, de acuerdo con las condiciones aplicables. Cada solicitud será evaluada según su naturaleza y el marco vigente.'] },
  { id: 'menores', title: 'Menores de edad', paragraphs: ['Los servicios y canales generales no están dirigidos a recopilar deliberadamente información de menores de edad. Si se requiriera tratarla para un proyecto específico, deberán observarse las autorizaciones y salvaguardas correspondientes.'] },
  { id: 'modificaciones', title: 'Modificaciones de la política', paragraphs: ['Esta política podrá actualizarse cuando cambien el sitio, los canales, las prácticas de tratamiento o las obligaciones aplicables. La versión publicada indicará su fecha de actualización.'] },
  { id: 'contacto', title: 'Contacto', paragraphs: ['Para consultas generales relacionadas con esta política puede escribirse a neoredescol@gmail.com o comunicarse por WhatsApp al +57 320 552 0676. El uso de estos datos como canal formal para ejercer derechos debe confirmarse antes de la publicación jurídica definitiva.'] },
]
</script>
<template><LegalPageLayout eyebrow="DOCUMENTO LEGAL" title-top="POLÍTICA DE" title-accent="PRIVACIDAD" intro="Información clara sobre el uso y cuidado de los datos compartidos con NEO REDES." :updated-at="updatedAt" :sections="sections" /></template>
