<script setup lang="ts">
useSeoMeta({ title: 'NEO REDES', description: 'Condiciones generales de acceso al sitio web y solicitud de servicios de NEO REDES.' })
const updatedAt = '26 de agosto de 2026'
const sections = [
  { id: 'identificacion-aceptacion', title: 'Identificación y aceptación', paragraphs: ['Estos términos regulan el acceso y uso del sitio de NEO REDES. La identificación jurídica completa del titular del sitio está pendiente de confirmación y deberá incorporarse antes de su publicación jurídica definitiva. Al navegar se aceptan las condiciones aplicables al uso del sitio.'] },
  { id: 'objeto-sitio', title: 'Objeto del sitio web', paragraphs: ['El sitio presenta información institucional, servicios creativos y digitales, planes orientativos, proyectos y canales de contacto. Su contenido general no sustituye una propuesta, contrato o asesoría profesional específica.'] },
  { id: 'uso-permitido', title: 'Uso permitido', paragraphs: ['La persona usuaria deberá utilizar el sitio de manera lícita, respetar los derechos de terceros y abstenerse de interferir con su funcionamiento, seguridad o disponibilidad.'] },
  { id: 'propiedad-intelectual', title: 'Propiedad intelectual', paragraphs: ['Los elementos propios creados para NEO REDES se encuentran sujetos a las reglas de propiedad intelectual aplicables. Los logos, marcas, fotografías y materiales de clientes, aliados u otros terceros pertenecen a sus respectivos titulares y su aparición no transfiere derechos sobre ellos.'] },
  { id: 'informacion-servicios', title: 'Información sobre servicios', paragraphs: ['Las descripciones publicadas tienen carácter informativo. El alcance definitivo dependerá de la propuesta o acuerdo aceptado para cada proyecto.'] },
  { id: 'solicitudes-contratacion', title: 'Solicitudes y contratación de servicios', paragraphs: ['Enviar una consulta no crea por sí solo una relación contractual. La contratación se producirá cuando las partes acepten las condiciones particulares mediante el mecanismo que definan para cada servicio.'] },
  { id: 'cotizaciones', title: 'Cotizaciones y propuestas', paragraphs: ['Cada propuesta podrá precisar alcance, entregables, valor, cronograma, responsabilidades y vigencia. En caso de diferencia, las condiciones particulares aceptadas prevalecerán sobre la información general del sitio.'] },
  { id: 'pagos', title: 'Pagos', paragraphs: ['Los valores, moneda, forma y fechas de pago serán los establecidos en la propuesta o acuerdo correspondiente. La publicación de un plan no incorpora condiciones de pago adicionales no pactadas.'] },
  { id: 'obligaciones-cliente', title: 'Obligaciones del cliente', paragraphs: ['El cliente deberá suministrar oportunamente información, accesos, autorizaciones, aprobaciones y materiales necesarios, y garantizar que puede utilizar aquello que entrega para el proyecto.'] },
  { id: 'entrega-materiales', title: 'Entrega de materiales', paragraphs: ['Los formatos, medios y fechas para entregar materiales se definirán según el proyecto. Retrasos o insuficiencias podrán afectar el cronograma y deberán gestionarse entre las partes.'] },
  { id: 'tiempos-ejecucion', title: 'Tiempos de ejecución', paragraphs: ['Los tiempos serán los indicados en la propuesta o planificación aceptada y podrán depender de la entrega de insumos, aprobaciones, disponibilidad y alcance definitivo.'] },
  { id: 'modificaciones-revisiones', title: 'Modificaciones y revisiones', paragraphs: ['La cantidad y alcance de revisiones no se presume a partir del sitio. Se determinarán en cada propuesta; solicitudes adicionales podrán requerir una actualización de alcance, tiempo o valor.'] },
  { id: 'servicios-terceros', title: 'Servicios de terceros', paragraphs: ['Algunos proyectos pueden requerir plataformas, licencias o proveedores externos. Su uso, costo, disponibilidad y condiciones deberán definirse expresamente cuando formen parte del servicio.'] },
  { id: 'cancelaciones', title: 'Cancelaciones', paragraphs: ['Las condiciones de cancelación, terminación, reprogramación y efectos económicos serán las pactadas para cada servicio. No se establece desde este sitio una política general de devoluciones o penalizaciones.'] },
  { id: 'responsabilidad', title: 'Responsabilidad', paragraphs: ['NEO REDES procurará prestar los servicios acordados con diligencia. Los resultados pueden depender de factores externos, decisiones del cliente, plataformas de terceros y condiciones de mercado, por lo que no se garantizan resultados no incluidos expresamente en un acuerdo.'] },
  { id: 'enlaces-externos', title: 'Enlaces externos', paragraphs: ['Los enlaces a sitios o plataformas externas se ofrecen para facilitar contacto o ampliar información. NEO REDES no controla su disponibilidad, seguridad, contenido ni políticas.'] },
  { id: 'contenido-terceros', title: 'Contenido de terceros', paragraphs: ['Las marcas y materiales de clientes, aliados y terceros se muestran respetando sus derechos. Su presencia no implica que NEO REDES sea titular de dichos activos.'] },
  { id: 'modificaciones-terminos', title: 'Modificaciones de los términos', paragraphs: ['Estos términos podrán actualizarse cuando cambien el sitio, los servicios o las condiciones aplicables. La versión publicada mostrará su última fecha de actualización.'] },
  { id: 'legislacion', title: 'Legislación aplicable', paragraphs: ['La definición precisa de legislación, jurisdicción y domicilio contractual requiere la identificación jurídica completa y revisión profesional. Estas referencias deben validarse antes de publicar la versión jurídica definitiva para Colombia.'] },
  { id: 'contacto', title: 'Contacto', paragraphs: ['Para consultas generales puede escribirse a neoredescol@gmail.com o comunicarse por WhatsApp al +57 320 552 0676. Las condiciones de un servicio se confirmarán en su propuesta o acuerdo particular.'] },
]
</script>
<template><LegalPageLayout eyebrow="CONDICIONES DE USO" title-top="TÉRMINOS Y" title-accent="CONDICIONES" intro="Reglas generales para utilizar el sitio y solicitar servicios a NEO REDES." :updated-at="updatedAt" :sections="sections" /></template>
